FROM node:14.17.1-stretch

RUN apt-get -qq update \
  && apt-get install --no-install-recommends -qqy yarn \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY ./src /usr/src/app

COPY package.json /usr/src/app/
COPY yarn.lock /usr/src/app/

RUN yarn install --production &&\
    yarn cache clean -y