#!/bin/bash

WRAPPER_PATH=$(readlink -f /usr/bin/google-chrome)
BASE_PATH="$WRAPPER_PATH-base"
mv "$WRAPPER_PATH" "$BASE_PATH"

cat > "$WRAPPER_PATH" <<_EOF
#!/bin/bash
# Note: exec -a below is a bashism.
_kill_procs() {
  kill -TERM $chromium
  wait $chromium
}
trap _kill_procs SIGTERM
exec -a "\$0" "$BASE_PATH" --no-sandbox --disable-dev-shm-usage "\$@" &
chromium=$!
wait $chromium
_EOF
chmod +x "$WRAPPER_PATH"