name: build project
on: 
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: '14.x'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: |
          yarn build &&\
          yarn publish --new-version $RELEASE_VERSION --no-git-tag-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: build docker images
        run: |
          docker build -f docker/Dockerfile.base . -t copper/base \
          && docker build -f docker/Dockerfile.hub . -t copper/hub \
          && docker build -f docker/Dockerfile.node-base . -t copper/node-base \
          && docker build -f docker/Dockerfile.node-headless . -t copper/node-headless \
          && docker build -f docker/Dockerfile.node . -t copper/node \
          && docker build -f docker/Dockerfile.standalone . -t copper/standalone \
          && docker build -f docker/Dockerfile.standalone-headless . -t copper/standalone-headless