name: test project
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v12
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm run lint
      - run: npm run test